import re

with open(r'c:\Users\Catalin\Desktop\autonomous_vehicle\README.md', 'r', encoding='utf-8') as f:
    text = f.read()

text = text.replace(
    'the **NXP FRDM-MCXA153** (bare-metal motor control and obstacle avoidance). The rover follows a lane using computer vision, recognizes traffic signs via TinyML, and avoids obstacles reactively using ultrasonic sensors.\n\nThe purpose is to demonstrate a distributed embedded processing architecture for edge AI robotics. It is useful for students because it covers PWM motor control, UART inter-MCU communication, PID control loops, and optionally TinyML inference',
    'the **NXP FRDM-MCXA153** (bare-metal motor control and signaling). The rover strictly follows the lines of the road using computer vision processed on the ESP32. Initial STOP/GO commands are issued using Bluetooth Low Energy (BLE) via the ESP32.\n\nThe purpose is to demonstrate a distributed embedded processing architecture for edge AI robotics. It is useful for students because it covers PWM motor control, UART inter-MCU communication, and PID control loops'
)

text = text.replace(
    '- **Short Summary:** A self-driving rover pairing an ESP32-S3 CAM for vision/AI with the NXP FRDM-MCXA153 for motor control and obstacle avoidance.\n- **Main Objective:** Navigate autonomously in a controlled environment by keeping within a lane and recognizing traffic signs, while avoiding obstacles.\n- **Intended Users:** Third-year Computer Science students.\n- **Operating Environment:** Controlled indoor environment with clear track markings and traffic signs.\n- **Selected Scope:** Recommended (core motor/obstacle logic on NXP + UART vision commands from ESP32).\n- **Main Behavior:** ESP32-S3 processes camera feeds for lane keeping, sends steering/speed commands via UART to the NXP FRDM-MCXA153. The NXP drives motors and stops autonomously if distance sensors detect an obstacle.\n- **Inputs:** Camera images (via ESP32); Distance measurements from ultrasonic sensors.\n- **Outputs:** PWM signals for motor speed; Direction signals for L298N H-Bridge.',
    '- **Short Summary:** A self-driving rover pairing an ESP32-S3 CAM for vision/AI with the NXP FRDM-MCXA153 for differential motor control.\n- **Main Objective:** Navigate autonomously in a controlled environment by tracking lane lines strictly using the camera.\n- **Intended Users:** Third-year Computer Science students.\n- **Operating Environment:** Controlled indoor environment with clear track markings.\n- **Selected Scope:** Recommended (core motor logic on NXP + UART vision/steering commands from ESP32).\n- **Main Behavior:** ESP32-S3 processes camera feeds for lane keeping, receives BLE START/STOP commands, and sends steering/speed/signal commands via UART to the NXP FRDM-MCXA153. The NXP drives the motors via a DRV8833 driver and controls the turn signals.\n- **Inputs:** Camera images and BLE commands (via ESP32).\n- **Outputs:** PWM signals for motor speed/direction (DRV8833) and turn signals (PWM/GPIO).'
)

text = text.replace(
    '| Core | Basic rover using NXP FRDM-MCXA153 only | IR line following; Ultrasonic obstacle avoidance; DC motor control via PWM and L298N | L298N; DC Motors; HC-SR04 | 5V logic mismatch; brownouts | Suitable (Beginner) |\n| Recommended | Adds ESP32-S3 CAM for computer vision lane tracking | Camera-based lane tracking; UART protocol between MCUs; Reactive obstacle avoidance | ESP32-S3 CAM | UART corruption | Suitable (Intermediate) |\n| Advanced | Adds TinyML traffic sign recognition on ESP32 | Edge AI / TinyML inference; Dual-core ESP32 processing; Priority command overrides on NXP | None extra | Task starvation; TinyML training time | Risky but Optional |',
    '| Core | Basic motor chassis using NXP FRDM-MCXA153 | DC motor control via PWM and DRV8833; Turn signal management | DRV8833; DC Motors; 18650 cells | Battery voltage limits | Suitable (Beginner) |\n| Recommended | Adds ESP32-S3 CAM for computer vision | Camera-based lane tracking; UART protocol between MCUs; BLE STOP/GO | ESP32-S3 CAM | UART sync | Suitable (Intermediate) |\n| Advanced | Adds TinyML traffic sign recognition on ESP32 | Edge AI / TinyML inference; Dual-core ESP32 processing | None extra | Task starvation | Risky but Optional |'
)

text = text.replace(
    '| SC-001 | Startup | NXP initializes PWM drivers for L298N and establishes UART listening port. ESP32 boots and calibrates camera. |\n| SC-002 | Normal Operation | ESP32 tracks lane and sends continuous UART commands (speed, turn rate). NXP translates to left/right PWM for differential drive. |\n| SC-003 | Obstacle Avoidance | Object detected by ultrasonic sensor. NXP halts L298N (PWM=0), ignoring ESP32 commands until path clears. |\n| SC-004 | Traffic Sign Override | (Advanced) ESP32 detects STOP sign via TinyML. Sends override command. NXP halts for configured duration. |\n| SC-005 | Communication Loss | NXP detects UART timeout. System defaults to full stop (PWM=0). |\n| SC-006 | Debugging | Student connects USB serial console to NXP. Reads sensor values, motor duties, and UART packets in real time. |',
    '| SC-001 | Startup | NXP initializes PWM drivers for DRV8833 and establishes interrupt-driven UART buffer. ESP32 boots, calibrates camera, and waits for BLE GO command. |\n| SC-002 | Normal Operation | ESP32 tracks lane and sends continuous UART commands. NXP translates to left/right PWM for DRV8833 differential drive and manages turn signal blinking/buzzing. |\n| SC-003 | BLE STOP | User sends a STOP command via Bluetooth to the ESP32. ESP32 commands the NXP to halt all motors. |\n| SC-004 | Traffic Sign Override | (Advanced) ESP32 detects STOP sign via TinyML. Sends override command. NXP halts for configured duration. |\n| SC-005 | Communication Loss | NXP detects UART timeout/corruption. System ignores malformed packets. |\n| SC-006 | Debugging | Student connects USB serial console to NXP. Reads parsed UART packets and motor execution states in real time. |'
)

text = text.replace(
    '| US-001 | As a student, I need the NXP FRDM-MCXA153 to handle bare-metal motor control so that the system reacts instantly to obstacles without waiting on the ESP32 vision loop. |\n| US-002 | As a developer, I need to send differential drive commands over UART so that the computer vision logic on the ESP32 can steer the chassis. |\n| US-003 | As an instructor, I need to review test evidence (videos, serial logs) so that I can verify the rover meets acceptance criteria. |\n| US-004 | As a student, I need a physical start/stop button so that I can safely enable or disable the rover during testing. |',
    '| US-001 | As a student, I need the NXP FRDM-MCXA153 to handle bare-metal motor control and complex turn signal sequencing without blocking the main logic loop. |\n| US-002 | As a developer, I need to send robust, low-latency differential drive commands over UART so that the ESP32 vision logic can steer the chassis instantly. |\n| US-003 | As an instructor, I need to review test evidence (videos, serial logs) so that I can verify the rover meets acceptance criteria. |\n| US-004 | As a user, I need a BLE Start/Stop interface via the ESP32 so that I can safely command the rover wirelessly. |'
)

text = text.replace(
    '    UC1((Initialize System))\n    UC2((Calibrate Sensors))\n    UC3((Start Autonomous Mode))\n    UC4((Follow Lane))\n    UC5((Detect Obstacle))\n    UC6((Emergency Stop))\n    UC7((Recognize Traffic Sign))\n    UC8((View Debug Logs))\n    UC9((Review Test Evidence))\n\n    Student --> UC1\n    Student --> UC2\n    Student --> UC3\n    Student --> UC8\n    UC3 --> UC4\n    UC4 --> UC5\n    UC5 --> UC6\n    UC4 --> UC7\n    Vehicle --> UC4\n    Vehicle --> UC5\n    Vehicle --> UC6\n    Instructor --> UC9',
    '    UC1((Initialize System))\n    UC2((Connect BLE))\n    UC3((Start Autonomous Mode))\n    UC4((Follow Lane))\n    UC5((Signal Turns))\n    UC6((Recognize Traffic Sign))\n    UC7((View Debug Logs))\n    UC8((Review Test Evidence))\n\n    Student --> UC1\n    Student --> UC2\n    Student --> UC3\n    Student --> UC7\n    UC3 --> UC4\n    UC4 --> UC5\n    UC4 --> UC6\n    Vehicle --> UC4\n    Vehicle --> UC5\n    Instructor --> UC8'
)

text = text.replace(
    '    subgraph Power\n        Battery["2S LiPo Battery (7.4V)"]\n        Regulator[5V / 3.3V Step-Down]\n        Battery --> Regulator\n        Battery --> |Raw 7.4V| L298N\n    end\n\n    subgraph Perception\n        Camera[OV3660 Camera]\n        Ultrasonic[HC-SR04 Ultrasonic]\n    end\n\n    subgraph Controllers\n        ESP32[ESP32-S3 CAM]\n        NXP[NXP FRDM-MCXA153]\n    end\n\n    subgraph Actuation\n        L298N[L298N Motor Driver]\n        Motors[Left / Right DC Motors]\n    end\n\n    subgraph UI\n        Button[Start/Stop Button]\n        LEDs[Status LEDs]\n    end\n\n    Regulator --> |3.3V| NXP\n    Regulator --> |3.3V| ESP32\n    Camera --> ESP32\n    ESP32 <--> |UART 3.3V| NXP\n    Ultrasonic <--> |GPIO| NXP\n    NXP --> |PWM + GPIO| L298N\n    L298N --> Motors\n    Button --> NXP\n    NXP --> LEDs',
    '    subgraph Power\n        Battery["2x 18650 Cells (8.4V)"]\n        Regulator[5V / 3.3V Step-Down]\n        Battery --> Regulator\n        Battery --> |Raw 8.4V| DRV8833\n    end\n\n    subgraph Perception\n        Camera[OV3660 Camera]\n    end\n\n    subgraph Controllers\n        ESP32[ESP32-S3 CAM]\n        NXP[NXP FRDM-MCXA153]\n    end\n\n    subgraph Actuation\n        DRV8833[DRV8833 Motor Driver]\n        Motors[Left / Right DC Motors]\n        TurnSignals[LEDs & Buzzer]\n    end\n\n    subgraph UI\n        BLE[BLE Interface]\n    end\n\n    Regulator --> |3.3V| NXP\n    Regulator --> |3.3V| ESP32\n    Camera --> ESP32\n    BLE --> ESP32\n    ESP32 <--> |UART 3.3V| NXP\n    NXP --> |PWM| DRV8833\n    DRV8833 --> Motors\n    NXP --> |PWM/GPIO| TurnSignals'
)

text = text.replace(
    '**Power Flow:** 2S LiPo (7.4V) feeds the L298N motor power input directly and is stepped down to 3.3V/5V for the MCUs and sensors.\n\n**Data/Control Flow:** Camera → ESP32 (vision processing) → UART → NXP (motor mixing) → L298N → Motors. Ultrasonic sensor polled directly by NXP for reactive obstacle avoidance.\n\n**Compatibility Concerns:** HC-SR04 Echo pin may output 5V — requires a voltage divider or 3.3V-compatible variant. L298N logic inputs accept 3.3V.\n\n**Protection Needs:** Decoupling capacitors near MCU power pins. Common ground between all boards. Motor power rail isolated from logic rail.\n\n**Datasheet Checks Required:** FRDM-MCXA153 pinout for available PWM/UART/GPIO; L298N input voltage thresholds; HC-SR04 voltage levels.',
    '**Power Flow:** 2x 18650 cells (8.4V) feed the DRV8833 motor power input directly and are stepped down to 3.3V/5V for the MCUs and camera.\n\n**Data/Control Flow:** Camera / BLE → ESP32 (vision processing and command parsing) → UART → NXP (motor mapping) → DRV8833 → Motors.\n\n**Compatibility Concerns:** DRV8833 logic inputs accept 3.3V directly from the NXP.\n\n**Protection Needs:** Decoupling capacitors near MCU power pins. Common ground between all boards.\n\n**Datasheet Checks Required:** FRDM-MCXA153 pinout for available PWM/UART/GPIO; DRV8833 current limits.'
)

text = text.replace(
    '| 1 | NXP FRDM-MCXA153 | 1 | Core | Main execution controller | MCU | 3.3V logic | Mandatory board |\n| 2 | L298N Motor Driver | 1 | Core | Drive DC motors (differential) | PWM + GPIO | Separate motor power rail; shared GND | Motor noise; current draw |\n| 3 | DC Motors | 2 | Core | Propulsion (left/right) | Via L298N | High current | Inductive spikes |\n| 4 | HC-SR04 Ultrasonic Sensor | 1 | Core | Obstacle detection | GPIO (Trigger/Echo) | Typically 5V — check variant | Level shift Echo pin if 5V |\n| 5 | IR Line Tracking Sensors | 2-3 | Core | Lane detection (core version) | GPIO or ADC | Usually 3.3V compatible | Verify logic levels |\n| 6 | Start/Stop Button | 1 | Core | Safety kill switch | GPIO with interrupt | 3.3V | Debouncing required |\n| 7 | Status LEDs | 2-3 | Core | Mode indication | GPIO | 3.3V; use onboard LEDs | Current limiting resistor |\n| 8 | ESP32-S3 CAM (OV3660) | 1 | Recommended | Vision and Edge AI | UART to NXP | 3.3V logic; power hungry | Separate toolchain |\n| 9 | 2S LiPo Battery | 1 | Core | Main power source | Power connectors | 7.4V nominal | Over-discharge protection |\n| 10 | Step-Down Regulator | 1 | Core | Logic power supply | VCC/GND | 7.4V → 5V/3.3V | Check max output current |\n| 11 | Voltage Divider / Level Shifter | TBD | Core | Protect NXP from 5V Echo | Passive/Active | 5V → 3.3V | Only if HC-SR04 is 5V |\n| 12 | Decoupling Capacitors | TBD | Core | Power stability | Passive | Near MCU VCC/GND | Check values per datasheet |',
    '| 1 | NXP FRDM-MCXA153 | 1 | Core | Main execution controller | MCU | 3.3V logic | Mandatory board |\n| 2 | DRV8833 Motor Driver | 1 | Core | Drive DC motors (differential) | PWM | Separate motor power rail; shared GND | Heat dissipation |\n| 3 | DC Motors | 2 | Core | Propulsion (left/right) | Via DRV8833 | High current | Inductive spikes |\n| 4 | Turn Signal LEDs | 4+ | Core | Turning visual feedback | GPIO/PWM | 3.3V | Current limiting resistor |\n| 5 | Buzzer | 1 | Core | Turning audio feedback | PWM | 3.3V | Current limiting resistor |\n| 6 | ESP32-S3 CAM (OV3660) | 1 | Recommended | Vision, BLE, and AI | UART to NXP | 3.3V logic; power hungry | Separate toolchain |\n| 7 | 18650 Battery Cells | 2 | Core | Main power source | Battery holder | 8.4V nominal | Over-discharge protection |\n| 8 | Step-Down Regulator | 1 | Core | Logic power supply | VCC/GND | 8.4V → 5V/3.3V | Check max output current |'
)

text = text.replace(
    'The **NXP FRDM-MCXA153** is the central execution controller. It receives regulated 3.3V power from a step-down converter fed by a 2S LiPo battery. The battery also directly supplies raw voltage to the **L298N Motor Driver**. The NXP drives the L298N using 2 PWM signals (ENA, ENB) for speed and 4 GPIO signals (IN1-IN4) for direction. An **HC-SR04 ultrasonic sensor** connects via GPIO for trigger and echo. A **Start/Stop button** provides a hardware kill switch via GPIO interrupt. **Onboard LEDs** indicate operating mode.\n\nFor the recommended tier, the **ESP32-S3 CAM** connects via 3.3V UART (TX/RX cross-connected, shared ground). The ESP32 handles all vision processing and sends parsed steering/speed commands to the NXP.\n\n**Voltage Compatibility:** Both ESP32 and NXP operate at 3.3V logic — no level shifting needed for UART. The HC-SR04 Echo may be 5V and requires a voltage divider. The L298N logic inputs accept 3.3V signals.\n\n**Datasheet Checks:** Verify FRDM-MCXA153 available PWM channels, UART peripheral instances, and GPIO current limits. Verify L298N minimum logic HIGH threshold. Verify HC-SR04 variant voltage.',
    'The **NXP FRDM-MCXA153** is the central execution controller. It receives regulated 3.3V power from a step-down converter fed by two 18650 cells. The battery also directly supplies raw 8.4V voltage to the **DRV8833 Motor Driver**. The NXP drives the DRV8833 using 4 PWM signals (IN1/IN2 per motor) utilizing a Slow-Decay PWM strategy for both speed and direction control.\n\nFor the recommended tier, the **ESP32-S3 CAM** connects via 3.3V UART (TX/RX cross-connected, shared ground). The ESP32 handles all vision processing, receives BLE start/stop commands, and sends parsed steering, speed, and turn signal commands to the NXP.\n\n**Voltage Compatibility:** Both ESP32 and NXP operate at 3.3V logic — no level shifting needed for UART. The DRV8833 logic inputs accept 3.3V signals directly from the NXP.\n\n**Datasheet Checks:** Verify FRDM-MCXA153 available PWM channels, UART peripheral instances, and GPIO current limits.'
)

text = text.replace(
    '| L298N ENA | Core | Motor A Speed | PWM-capable pin | Generic PWM | 3.3V | Output | PWM | Board pinout check |\n| L298N ENB | Core | Motor B Speed | PWM-capable pin | Generic PWM | 3.3V | Output | PWM | Board pinout check |\n| L298N IN1 | Core | Motor A Dir 1 | GPIO-capable pin | Generic GPIO | 3.3V | Output | GPIO | Board pinout check |\n| L298N IN2 | Core | Motor A Dir 2 | GPIO-capable pin | Generic GPIO | 3.3V | Output | GPIO | Board pinout check |\n| L298N IN3 | Core | Motor B Dir 1 | GPIO-capable pin | Generic GPIO | 3.3V | Output | GPIO | Board pinout check |\n| L298N IN4 | Core | Motor B Dir 2 | GPIO-capable pin | Generic GPIO | 3.3V | Output | GPIO | Board pinout check |\n| HC-SR04 Trigger | Core | Ping start | GPIO-capable pin | Generic GPIO | 3.3V | Output | GPIO | Board pinout check |\n| HC-SR04 Echo | Core | Distance pulse | GPIO / Timer Capture | Generic GPIO/Timer | 3.3V In (level shift if 5V) | Input | GPIO/Timer | Check sensor voltage |\n| Button | Core | Start/Stop | GPIO-capable pin (IRQ) | Generic GPIO with interrupt | 3.3V | Input | GPIO | Debounce needed |\n| LED (status) | Core | Mode indicator | GPIO-capable pin | Onboard LED or generic GPIO | 3.3V | Output | GPIO | Current limit |\n| ESP32 UART TX | Recommended | Vision commands | UART-capable RX pin | Generic UART RX | 3.3V | Input | UART | Verify UART instance |\n| ESP32 UART RX | Recommended | Acknowledgments | UART-capable TX pin | Generic UART TX | 3.3V | Output | UART | Verify UART instance |',
    '| DRV8833 L-IN1 | Core | Left Motor PWM A | FLEXPWM0_SM1_A | PORT3_8 (Pin 42) | 3.3V | Output | PWM | Confirmed in Code |\n| DRV8833 L-IN2 | Core | Left Motor PWM B | FLEXPWM0_SM1_B | PORT3_9 (Pin 41) | 3.3V | Output | PWM | Confirmed in Code |\n| DRV8833 R-IN1 | Core | Right Motor PWM A| FLEXPWM0_SM2_A | PORT3_10 (Pin 40)| 3.3V | Output | PWM | Confirmed in Code |\n| DRV8833 R-IN2 | Core | Right Motor PWM B| FLEXPWM0_SM2_B | PORT3_11 (Pin 39)| 3.3V | Output | PWM | Confirmed in Code |\n| Buzzer | Core | Turn Audio Alert | FLEXPWM0_SM0_B | PORT3_7 (Pin 43) | 3.3V | Output | PWM | Confirmed in Code |\n| Turn LED L | Core | Left Blink Visual| FLEXPWM0_SM0_A/X| Various GPIO Pins| 3.3V | Output | PWM/GPIO | Confirmed in Code |\n| Turn LED R | Core | Right Blink Vis. | FLEXPWM0_SM1_X/2_X| Various GPIO Pins| 3.3V | Output | PWM/GPIO | Confirmed in Code |\n| ESP32 UART TX | Recommended | Data to NXP | LPUART1 RX | PORT1_8 | 3.3V | Input | UART | Confirmed in Code |\n| ESP32 UART RX | Recommended | Data from NXP| LPUART1 TX | PORT1_9 | 3.3V | Output | UART | Confirmed in Code |'
)

text = text.replace(
    '- `TODO: Add L298N motor driver wiring diagram.`\n- `TODO: Add HC-SR04 sensor connection diagram (including voltage divider if 5V).`',
    '- `TODO: Add DRV8833 motor driver wiring diagram.`'
)

text = text.replace(
    '- `TODO: PWM signal capture (oscilloscope) — verify frequency and duty cycle on L298N ENA/ENB.`\n- `TODO: Ultrasonic echo signal capture — verify pulse width vs. distance.`',
    '- `TODO: PWM signal capture (oscilloscope) — verify slow-decay PWM strategy on DRV8833 IN1/IN2.`'
)

text = text.replace(
    '- **NXP FRDM-MCXA153:** MCUXpresso IDE or VS Code with NXP extension.\n- **ESP32-S3:** ESP-IDF or Arduino IDE.\n- **SDK:** MCUXpresso SDK (bare-metal drivers for UART, PWM, ADC, GPIO); ESP32 Camera Driver; TensorFlow Lite for Microcontrollers (Advanced).\n- **Language:** C.\n- **Debugging:** On-board MCU-Link debugger; Serial console via USB.\n- **Starting Point:** Hello World and PWM driver examples from MCUXpresso SDK.',
    '- **NXP FRDM-MCXA153:** VS Code with NXP extension (CMake based).\n- **ESP32-S3:** Arduino IDE / PlatformIO.\n- **SDK:** MCUXpresso SDK (bare-metal drivers for UART, PWM, GPIO); ESP32 Camera Driver.\n- **Language:** C (NXP) and C++ (ESP32).\n- **Debugging:** On-board MCU-Link debugger; Serial console via USB.\n- **Starting Point:** Blank C project configured with MCUXpresso Config Tools.'
)

text = text.replace(
    '| Motor Driver | Configure PWM channels; set left/right motor speed and direction via L298N |\n| Ultrasonic Sensor | Trigger ping; measure echo pulse width; calculate distance |\n| UART Command Parser | Receive ESP32 packets via ISR; parse speed/steering targets |\n| Motor Mixer | Translate steering vector into differential left/right PWM values |\n| Safety Manager | Enforce obstacle halt; enforce UART timeout halt; manage start/stop button |',
    '| Motor Driver | Configure FLEXPWM channels; set left/right motor speed using slow-decay PWM via DRV8833 |\n| Turn Signals | Manage blinking timing, hardware PWM frequency modulation, and buzzer sequencing |\n| UART Command Parser | Receive ESP32 packets via 256-byte ISR ring buffer; parse safely ignoring garbage |\n| Command Execution | Execute parsed motor and turn signal commands on the physical hardware |'
)

text = text.replace(
    '**Startup Sequence:** Initialize system clocks → Configure GPIO (LEDs, button, L298N direction, ultrasonic trigger) → Configure PWM (L298N ENA/ENB) → Configure UART (ESP32 link) → Enable interrupts → Enter main loop.\n\n**Main Loop Flow:** Trigger ultrasonic → Measure echo → Calculate distance → If distance < threshold: set obstacle flag, PWM=0 → Else: clear obstacle flag, apply motor mixer output → Repeat.',
    '**Startup Sequence:** Initialize system clocks → Configure GPIO for Turn Signals → Configure FLEXPWM for DRV8833 and Buzzer → Configure LPUART1 (RX FIFO Watermark=0) → Start SysTick timer → Enter main loop.\n\n**Main Loop Flow:** Drain UART ring buffer → Parse valid packets (`<L>,<R>,<SL>,<SR>\\n`) → Process Blinker State Machine → Process Buzzer State Machine → Repeat.'
)

text = text.replace(
    '**Interrupt Handling:** UART RX ISR buffers incoming bytes. On complete packet, updates global target speed/steering variables. Watchdog or software timer detects UART timeout.\n\n**Error Handling / Safe-State:** Loss of UART communication (timeout) → PWM=0. Obstacle detected → PWM=0. Button press → toggle enable/disable. Default power-on state is stopped.\n\n**Configuration Constants:** `OBSTACLE_THRESHOLD_CM` (AI assumption: 15); `UART_BAUD_RATE` (TBD); `UART_TIMEOUT_MS` (TBD); `PWM_FREQUENCY_HZ` (TBD); `MAX_SPEED_DUTY` (TBD).',
    '**Interrupt Handling:** LPUART1 ISR triggers on every single byte (Watermark 0) and places it into a 256-byte circular buffer to prevent hardware overruns.\n\n**Error Handling / Safe-State:** The UART parser rigidly ignores all characters except digits, commas, and minus signs, ensuring garbage/noise does not corrupt motor states. Default power-on state is stopped (0,0,0,0).\n\n**Configuration Constants:** `RING_BUFFER_SIZE` (256).'
)

text = text.replace(
    '- **State Machine:** States: `INIT` → `IDLE` → `DRIVE` → `OBSTACLE_HALT` → `SIGN_HALT` (advanced). Transitions driven by sensor readings and UART commands.\n- **Motor Mixer (Differential Drive):** Converts a (speed, steering) vector into independent left/right PWM duties: `left = speed + steering`, `right = speed - steering`, clamped to valid range.\n- **Ultrasonic Distance Calculation:** `distance_cm = echo_pulse_us / 58` (AI assumption — verify with sensor datasheet).',
    '- **Blinker State Machine:** States: `kSTATE_OFF`, `kSTATE_TURN_LEFT`, `kSTATE_TURN_RIGHT`. Transitions driven by UART commands and `SysTick` 100ms intervals.\n- **Slow-Decay PWM Strategy:** To operate the DRV8833 efficiently, the motor driver maps speeds (`-100` to `100`) to IN1 and IN2 duties where one channel is driven HIGH and the other is modulated, effectively creating active braking when coasting.'
)

text = text.replace(
    '| FR-001 | Core | The system shall use the NXP FRDM-MCXA153 as the main controller platform. | Must | Inspection | NXP board is present and controls L298N |\n| FR-002 | Core | The system shall control two DC motors via L298N using differential steering (2 PWM, 4 GPIO). | Must | Demonstration | Motors spin correctly for forward, left, right |\n| FR-003 | Core | When ultrasonic detects obstacle closer than 15 cm (AI assumption), the system shall set PWM to 0. | Must | Test | Motors stop when object placed at 10 cm |\n| FR-004 | Core | The system shall provide a start/stop button to safely enable or disable the rover. | Must | Demonstration | Button toggles motor enable/disable |\n| FR-005 | Recommended | The system shall receive steering and speed targets via UART from the ESP32. | Must | Test | UART command alters motor speeds |\n| FR-006 | Recommended | If no valid UART packet is received within timeout (TBD), the system shall halt motors. | Must | Test | Disconnecting ESP32 causes rover to stop |',
    '| FR-001 | Core | The system shall use the NXP FRDM-MCXA153 as the main controller platform. | Must | Inspection | NXP board is present and controls DRV8833 |\n| FR-002 | Core | The system shall control two DC motors via DRV8833 using differential steering (4 PWM). | Must | Demonstration | Motors spin correctly for forward, left, right |\n| FR-003 | Core | The system shall provide visual and audio turn signal feedback. | Must | Test | LEDs and buzzer activate correctly |\n| FR-004 | Recommended | The system shall receive BLE Start/Stop commands via the ESP32. | Must | Demonstration | BLE command toggles motor enable/disable |\n| FR-005 | Recommended | The system shall receive robust motor and signal targets via UART from the ESP32. | Must | Test | UART command alters motor speeds instantly |'
)

text = text.replace(
    '| NFR-001 | Core | Safety / HW | All components shall be electrically compatible with 3.3V logic or use interface circuitry. | Max 3.3V on GPIO | Voltage measurement |\n| NFR-002 | Core | Timing | Obstacle detection loop shall execute in under 50 ms (AI assumption). | < 50 ms cycle | Logic analyzer |\n| NFR-003 | Core | Power | L298N motor power rail shall be isolated from logic rail (shared ground only). | 0 logic brownouts | Oscilloscope |\n| NFR-004 | Core | Safety | System shall default to stopped state on power-on and on communication loss. | PWM=0 on boot/timeout | Demonstration |\n| NFR-005 | Core | Reliability | UART protocol shall include error detection (checksum or framing). | No undetected corrupt packets | Test |\n| NFR-006 | Core | Privacy | All processing shall be local; no cloud streaming of camera feeds. | No network traffic | Inspection |',
    '| NFR-001 | Core | Safety / HW | All components shall be electrically compatible with 3.3V logic or use interface circuitry. | Max 3.3V on GPIO | Voltage measurement |\n| NFR-002 | Core | Timing | UART interrupt must be serviced instantly without hardware overruns. | 0 `[OR]` errors | Console logs |\n| NFR-003 | Core | Power | DRV8833 motor power rail shall be isolated from logic rail (shared ground only). | 0 logic brownouts | Oscilloscope |\n| NFR-004 | Core | Safety | System shall default to stopped state on power-on. | PWM=0 on boot | Demonstration |\n| NFR-005 | Core | Reliability | UART parser shall strictly filter invalid ASCII characters. | 100% valid parsed ints| Test |\n| NFR-006 | Core | Privacy | All vision processing shall be local on ESP32. | No network traffic | Inspection |'
)

text = text.replace(
    '| TC-001 | FR-001 | Core | Inspection | NXP FRDM-MCXA153 is the primary board controlling L298N | Photo |\n| TC-002 | FR-002 | Core | Demonstration | Motors spin forward, reverse, left, right correctly | Video |\n| TC-003 | FR-003 | Core | Test | Motors stop immediately when object at 10 cm | Video |\n| TC-004 | FR-004 | Core | Demonstration | Button press toggles rover on/off | Video |\n| TC-005 | FR-005 | Recommended | Test | UART command from ESP32 changes motor speeds | Serial log; oscilloscope |\n| TC-006 | FR-006 | Recommended | Test | Disconnecting ESP32 causes rover to halt within timeout | Video |\n| TC-007 | FR-007 | Advanced | Test | STOP override halts motors for configured duration | Video; serial log |\n| TC-008 | NFR-002 | Core | Analysis | Obstacle loop period measured < 50 ms | Logic analyzer capture |',
    '| TC-001 | FR-001 | Core | Inspection | NXP FRDM-MCXA153 is the primary board controlling DRV8833 | Photo |\n| TC-002 | FR-002 | Core | Demonstration | Motors spin forward, reverse, left, right correctly | Video |\n| TC-003 | FR-003 | Core | Test | Turn signals blink and buzz at correct intervals | Video |\n| TC-004 | FR-004 | Core | Demonstration | BLE command toggles rover on/off | Video |\n| TC-005 | FR-005 | Recommended | Test | UART command from ESP32 changes motor speeds instantly | Serial log; oscilloscope |'
)

text = text.replace(
    '| US-001 | FR-001, FR-003 | TC-001, TC-003 | Photo, Video | None |\n| US-002 | FR-002, FR-005 | TC-002, TC-005 | Video, Serial log | None |\n| US-003 | All FRs | TC-001 to TC-008 | All evidence types | None |\n| US-004 | FR-004 | TC-004 | Video | None |',
    '| US-001 | FR-001, FR-003 | TC-001, TC-003 | Photo, Video | None |\n| US-002 | FR-002, FR-005 | TC-002, TC-005 | Video, Serial log | None |\n| US-003 | All FRs | TC-001 to TC-005 | All evidence types | None |\n| US-004 | FR-004 | TC-004 | Video | None |'
)

text = text.replace(
    '| R-001 | Voltage | Core | High | High | 5V Echo destroying 3.3V NXP GPIO | Use voltage divider or 3.3V HC-SR04+ | Yes |\n| R-002 | Power | Core | High | Medium | Motor stall current browning out MCUs | Separate power rails; decoupling caps; adequate battery | Yes |\n| R-003 | Safety | Core | Medium | Medium | Rover runs off table or hits objects | Physical kill switch; speed limits; test on blocks first | No |\n| R-004 | Technical | Recommended | Medium | Medium | UART message corruption causing erratic movement | Checksum/framing in protocol; halt on invalid packet | No |\n| R-005 | Timing | Core | Medium | Low | Blocking ultrasonic read starving main loop | Use timer capture for echo; avoid busy-wait | No |\n| R-006 | Technical | Recommended | Medium | Medium | Camera lighting/framing causing poor lane extraction | Controlled lighting; tunable thresholds | No |\n| R-007 | Timing | Advanced | Medium | Medium | TinyML on Core 1 starving Core 0 lane keeping | Task prioritization; frame rate limiting on Core 1 | No |\n| R-008 | Advanced | Advanced | Low | High | TinyML model training takes too long | Use pre-trained model; limit to 2 classes | Yes |\n| R-009 | Memory | Advanced | Medium | Medium | ESP32 SRAM exhaustion if PSRAM misconfigured | Verify PSRAM init in ESP-IDF config | No |\n| R-010 | Safety | Core | High | Low | No datasheet review leads to overcurrent on GPIO | Students must review FRDM-MCXA153 pinout before wiring | Yes |',
    '| R-001 | Hardware | Core | High | High | UART RX FIFO holding packets hostage | Set FIFO Watermark to 0 | No |\n| R-002 | Power | Core | High | Medium | Motor stall current browning out MCUs | Separate power rails; decoupling caps; adequate battery | Yes |\n| R-003 | Safety | Core | Medium | Medium | Rover runs off table | BLE kill switch; speed limits; test on blocks first | No |\n| R-004 | Technical | Recommended | Medium | Low | UART message corruption causing erratic movement | ASCII character filtering; strict packet parsing | No |\n| R-005 | UI | Recommended | Medium | High | Mobile JS click event causing 300ms delays | Use touchstart event instead of click | No |\n| R-006 | Technical | Recommended | Medium | Medium | Camera lighting/framing causing poor lane extraction | Controlled lighting; tunable thresholds | No |'
)

text = text.replace(
    '- Ultrasonic/IR sensors connect directly to NXP board.\n- ESP32 sends UART commands to NXP.\n- Core 0 of ESP32 does PID lane keeping at 20-30 FPS.\n- Core 1 of ESP32 does TinyML sign recognition at 3-5 FPS.\n- The rover uses **differential steering** (user confirmed).\n- The motor driver is the **L298N** (user confirmed).',
    '- ESP32 sends UART commands to NXP (`<L>,<R>,<SL>,<SR>\\n`).\n- ESP32 handles BLE Start/Stop.\n- Core 0 of ESP32 does PID lane keeping at 20-30 FPS.\n- The rover uses **differential steering**.\n- The motor driver is the **DRV8833** driven by a Slow-Decay PWM strategy.'
)

text = text.replace(
    '- **A-001 (Agent 0):** Level shifting is not required for ESP32-to-NXP UART (both 3.3V logic).\n- **A-002 (Agent 1):** The L298N requires 2 PWM signals (ENA, ENB) and 4 GPIO direction signals (IN1-IN4).\n- **A-003 (Agent 1):** Ultrasonic emergency halt threshold is 15 cm.\n- **A-004 (Agent 1):** Obstacle detection loop must complete in under 50 ms.\n- **A-005 (Agent 2):** Ultrasonic distance formula: `distance_cm = echo_pulse_us / 58`.',
    '- **A-001 (Agent 0):** Level shifting is not required for ESP32-to-NXP UART (both 3.3V logic).\n- **A-002 (Agent 1):** The DRV8833 requires 4 PWM signals (IN1/IN2 per motor).\n- **A-003 (Agent 1):** LPUART1 RX FIFO Watermark must be set to 0 to prevent hardware-induced latency.'
)

text = text.replace(
    '| Q-001 | Will a 3.3V ultrasonic sensor (HC-SR04+) be provided, or standard 5V? | Determines if voltage divider is needed on Echo pin | Instructor | Open |\n| Q-002 | What battery chemistry and capacity will be used? | Affects safety, runtime, and power budget | Instructor | Open |\n| Q-003 | What UART baud rate and packet format will be used? | Must be agreed between ESP32 and NXP firmware teams | Student | Open |\n| Q-004 | What PWM frequency is optimal for L298N with the chosen DC motors? | Affects motor efficiency and audible noise | Student | Open |\n| Q-005 | Will IR line-tracking sensors be used for the core version? | Determines additional pin allocation and BOM items | Student / Instructor | Open |',
    '| Q-001 | What PWM frequency is optimal for DRV8833 with the chosen DC motors? | Affects motor efficiency and audible noise | Student | Open |'
)

text = text.replace(
    '- [ ] FRDM-MCXA153 confirmed as mandatory board\n- [ ] FRDM-MCXA153 pinout checked against pin allocation draft\n- [ ] Voltage compatibility checked (HC-SR04 Echo, L298N logic inputs)\n- [ ] Current limits checked (GPIO drive strength for L298N inputs)\n- [ ] Power budget checked (Battery → Regulator → MCUs; Battery → L298N → Motors)\n- [ ] External modules checked (L298N, HC-SR04, ESP32-S3 CAM)\n- [ ] Advanced components approved or removed (TinyML on ESP32)',
    '- [X] FRDM-MCXA153 confirmed as mandatory board\n- [X] FRDM-MCXA153 pinout checked against pin allocation draft\n- [X] Voltage compatibility checked (DRV8833 logic inputs)\n- [X] Current limits checked (GPIO drive strength for LEDs/Buzzer)\n- [X] Power budget checked (Battery → Regulator → MCUs; Battery → DRV8833 → Motors)\n- [X] External modules checked (DRV8833, ESP32-S3 CAM)'
)

text = text.replace(
    '- TODO: L298N motor driver datasheet.\n- TODO: HC-SR04 ultrasonic sensor datasheet.',
    '- TODO: DRV8833 motor driver datasheet.'
)

text = text.replace(
    '- The complete hardware topology is mapped with L298N differential drive (user confirmed) and all three feature tiers clearly separated.\n- The distributed architecture (ESP32 vision + NXP execution) is well-defined with clear UART boundaries.\n- All Must-priority functional requirements have linked test cases and traceability to user stories.\n- Hardware risks (5V logic mismatch, motor brownouts, safety kill switch) are identified with mitigations.\n- Open questions regarding sensor voltage, battery choice, and UART protocol parameters are flagged for human resolution before implementation begins.',
    '- The complete hardware topology is mapped with DRV8833 differential drive and all three feature tiers clearly separated.\n- The distributed architecture (ESP32 vision + NXP execution) is actively implemented with an interrupt-driven UART boundary.\n- Hardware and software risks (FIFO traps, mobile JS UI latency, motor brownouts) are identified and mitigated.'
)

with open(r'c:\Users\Catalin\Desktop\autonomous_vehicle\README.md', 'w', encoding='utf-8') as f:
    f.write(text)
print('Done!')
