/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR12_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR16_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR4_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR5_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR7_MUX_mux101 0x05u /*!<@brief Pin Multiplex Control: Alternative 5 (chip-specific) */

/*! @name PORT3_0 (number 46), LED_BLUE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_4 (number 18), LED_BACK_LEFT_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BACK_LEFT_RED_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT3_12 (number 38), LED_RED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_6 (number 64), LED_FRONT_LEFT_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_FRONT_LEFT_RED_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT1_7 (number 1), LED_FRONT_LEFT_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_FRONT_LEFT_BLUE_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORT2_5 (number 19), LED_BACK_RIGHT_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BACK_RIGHT_RED_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT2_16 (number 24), LED_FRONT_RIGHT_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_FRONT_RIGHT_BLUE_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name PORT2_12 (number 22), LED_FRONT_RIGHT_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_FRONT_RIGHT_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PORT3_13 (number 37), LED_BACK_RIGHT_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BACK_RIGHT_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BACK_RIGHT_GREEN_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BACK_RIGHT_GREEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name PORT3_14 (number 36), LED_FRONT_RIGHT_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_FRONT_RIGHT_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_FRONT_RIGHT_GREEN_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_FRONT_RIGHT_GREEN_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name PORT3_7 (number 43), HORN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HORN_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HORN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HORN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_8 (number 42), MOTOR_LEFT_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_LEFT_1_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_LEFT_1_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_LEFT_1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_9 (number 41), MOTOR_LEFT_2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_LEFT_2_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_LEFT_2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_LEFT_2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_10 (number 40), MOTOR_RIGHT_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_RIGHT_1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_RIGHT_1_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_RIGHT_1_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT3_11 (number 39), MOTOR_RIGHT_2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_RIGHT_2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_RIGHT_2_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_RIGHT_2_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
